Repository prgrms-fe-devcourse/FEDC3_SWithMe_Gidong, pull requests merged in 2023-02, with the labels that each got.

#87 feat: 검색 이후 검색어 초기화
  src/components/domain/TemplateHeader/SearchBar.jsx
Labels: ✨ feat

#90 [feat] TIL 보기 페이지 로그인 하지 않은 사용자 처리
  src/api/post.js
  src/components/base/Icon/index.scss
  src/components/domain/AuthorNav/index.jsx
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CreateComment/index.jsx
  src/components/domain/FloatingLikeButton/index.jsx
  src/context/AuthProvider.jsx
  src/pages/TIL.jsx
  src/utils/group.js
  src/utils/post.js
  src/utils/validation.js
Labels: ✨ feat, :hammer: refactor

#93 [fix] 댓글 수정 시 storage id 변경
  src/components/domain/CommentItem/index.jsx
  src/context/CommentProvider.jsx
Labels: 🐛 fix, :hammer: refactor

#92 [feat] 검색 필터 드롭다운 닫기 이벤트 추가
  src/components/domain/TemplateHeader/SearchBar.jsx
Labels: ✨ feat

#95 [feat] 알림창 추가 기능 구현
  package.json
  src/api/alarm.js
  src/components/base/Avatar/index.jsx
  src/components/base/Badge/index.jsx
  src/components/base/Modal/index.jsx
  src/components/base/index.js
  src/components/domain/AlarmModal/index.jsx
  src/components/domain/SettingModal/index.jsx
  src/components/domain/TemplateHeader/NavIcon.jsx
  src/components/domain/TemplateHeader/UserNav.jsx
  src/components/domain/TemplateHeader/UserNav/Authorized.jsx
  src/components/domain/TemplateHeader/UserNav/NotAuthorized.jsx
  src/components/domain/TemplateHeader/UserNav/index.jsx
  src/components/domain/TemplateHeader/index.jsx
  src/components/template/index.jsx
  src/styles/color.js
  yarn.lock
Labels: ✨ feat, :hammer: refactor, 📡 API

#99 [feat] 페이지네이션 데이터 없을 경우 처리
  src/components/base/Pagination/index.jsx
Labels: ✨ feat

#97 [fix] 그룹원 제한 인원 초과 수정
  src/pages/JoinGroup.jsx
Labels: 🐛 fix, 🎨 design

#102 [fix] 읽지 않은 메시지가 없을 때 처리
  src/components/domain/AlarmModal/index.jsx
Labels: 🐛 fix

#104 [feat] 알림 설정 모달에서 설정 완료 후 모달 종료
  src/components/domain/SettingModal/index.jsx
Labels: ✨ feat

#105 [fix] 동일 그룹 명 생성 시 에러
  src/components/domain/CreateGroupModal/index.jsx
Labels: 🐛 fix

#107 [feat] Toast 구현 및 alert 변경
  package.json
  src/App.jsx
  src/components/base/Tag/index.jsx
  src/components/base/Toast/ToastItem.jsx
  src/components/base/Toast/index.jsx
  src/components/base/index.js
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/TemplateHeader/SearchBar.jsx
  src/context/ToastProvider.jsx
  src/hooks/useTimeout.js
  src/hooks/useTimeoutFn.js
  src/pages/ManageGroup.jsx
  src/pages/MyPage.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  yarn.lock
Labels: ✨ feat, 🎨 design

#110 [design] 검색 결과 페이지 스타일링 수정
  src/components/base/Pagination/index.jsx
  src/components/base/Text/index.jsx
  src/components/domain/SearchResult/SearchResultContainer.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/TILList/index.jsx
  src/pages/JoinGroup.jsx
  src/pages/SearchResult.jsx
Labels: ✨ feat, 🎨 design

#109 [feat] Input, TagInput, Textarea ref 방식에서 state 방식으로 변경
  src/components/base/Input/index.jsx
  src/components/base/Tag/index.jsx
  src/components/base/Textarea/index.jsx
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CreateComment/index.jsx
  src/components/domain/CreateGroupModal/index.jsx
  src/pages/ManageGroup.jsx
  src/pages/MyPage.jsx
  src/pages/TILEditor.jsx
  src/stories/components/base/Textarea.stories.jsx
Labels: ✨ feat

#116 [chore] 검색 아이콘 변경
  src/assets/icons/ic_search_submit.svg
  src/assets/icons/index.jsx
  src/components/base/Input/index.jsx
  src/components/base/Tag/index.jsx
  src/components/base/Textarea/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/TemplateHeader/Logo.jsx
  src/components/domain/TemplateHeader/SearchBar.jsx
Labels: 🍭 chore

#112 [feat] 그룹 정보 변경 없을시 수정 버튼 비활성화
  src/components/domain/ManageGroup/GroupDelete.jsx
  src/components/domain/ManageGroup/ManageMember.jsx
  src/components/domain/ManageGroup/UpdateGroupInfo.jsx
  src/components/domain/ManageGroup/index.jsx
  src/components/domain/ManageGroup/styles.jsx
  src/pages/ManageGroup.jsx
Labels: ✨ feat, :hammer: refactor

#114 [feat] 그룹 검색 결과 없을 경우 Empty 처리
  src/components/domain/SearchResult/SearchResultContainer.jsx
Labels: ✨ feat
