Repository prgrms-fe-devcourse/FEDC3_SWithMe_Gidong, pull requests merged in 2023-04, with the labels that each got.

#139 [refactor] base 컴포넌트 props 값 사전 정의 - 3
  src/components/base/Calendar/index.jsx
  src/components/base/Empty/index.jsx
  src/components/base/Icon/index.jsx
  src/components/base/Icon/styles.js
  src/components/base/Input/index.jsx
  src/components/base/Modal/index.jsx
  src/components/base/Modal/styles.js
  src/components/base/Pagination/index.jsx
  src/components/base/SearchBar/index.jsx
  src/components/base/Spinner/index.jsx
  src/components/base/Tag/TagInput.jsx
  src/components/base/Tag/TagItem.jsx
  src/components/base/Tag/TagList.jsx
  src/components/base/Tag/index.jsx
  src/components/base/Text/index.jsx
  src/components/base/Textarea/index.jsx
  src/components/base/Textarea/styles.js
  src/components/base/Toast/ToastItem.jsx
  src/components/base/Toast/index.jsx
  src/components/domain/AlarmModal/index.jsx
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CommentList/index.jsx
  src/components/domain/CreateComment/index.jsx
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/FloatingLikeButton/index.jsx
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/ManageGroup/GroupDelete.jsx
  src/components/domain/ManageGroup/UpdateGroupInfo.jsx
  src/components/domain/SearchResult/SearchResultContainer.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/SettingModal/index.jsx
  src/components/domain/SignInput/index.jsx
  src/components/domain/TILItem/index.jsx
  src/components/domain/TILList/index.jsx
  src/components/domain/TemplateHeader/UserNav/Authorized.jsx
  src/components/domain/groupInfo/Introduction.jsx
  src/components/domain/groupInfo/Member.jsx
  src/pages/Home.jsx
  src/pages/JoinGroup.jsx
  src/pages/MyGroup.jsx
  src/pages/MyPage.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/TIL.jsx
  src/styles/color.js
  src/styles/globalStyle.jsx
Labels: :hammer: refactor

#141 [refactor] base 컴포넌트 props 값 사전 정의 - 4
  src/components/base/Button/View.jsx
  src/components/base/Button/index.jsx
  src/components/base/Button/styles.js
  src/components/base/Input/index.jsx
  src/components/base/Input/styles.js
  src/components/base/SearchBar/index.jsx
  src/components/base/SearchBar/styles.js
  src/components/base/Tag/TagInput.jsx
  src/components/base/Tag/TagItem.jsx
  src/components/base/Tag/styles.js
  src/components/domain/AuthorNav/index.jsx
  src/components/domain/CreateComment/index.jsx
  src/components/domain/CreateComment/styles.js
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/CreateGroupModal/styles.js
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupInfoModal/styles.js
  src/components/domain/ManageGroup/GroupDelete.jsx
  src/components/domain/ManageGroup/ManageMember.jsx
  src/components/domain/ManageGroup/UpdateGroupInfo.jsx
  src/components/domain/ManageGroup/styles.js
  src/components/domain/MyPage/MyPageButton.jsx
  src/components/domain/MyPage/index.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/TILList/index.jsx
  src/components/domain/TILList/styles.js
  src/components/domain/TemplateHeader/SearchBar.jsx
  src/components/domain/TemplateHeader/UserNav/Authorized.jsx
  src/components/domain/TemplateHeader/UserNav/NotAuthorized.jsx
  src/components/domain/TemplateHeader/UserNav/index.jsx
  src/components/domain/TemplateHeader/styles.js
  src/pages/Home.jsx
  src/pages/MyGroup.jsx
  src/pages/MyPage.jsx
  src/pages/SignIn.jsx
  src/pages/TIL.jsx
  src/pages/TILEditor.jsx
Labels: :hammer: refactor

#147 [refactor] 그룹 관련 코드 리팩토링
  package.json
  src/App.jsx
  src/api/channel.js
  src/api/group.js
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/ManageGroup/GroupDelete.jsx
  src/components/domain/ManageGroup/ManageMember.jsx
  src/components/domain/ManageGroup/UpdateGroupInfo.jsx
  src/context/GroupProvider.jsx
  src/hooks/queries/group.js
  src/pages/Home.jsx
  src/pages/JoinGroup.jsx
  src/pages/ManageGroup.jsx
  src/pages/MyGroup.jsx
  src/pages/SearchResult.jsx
  src/utils/sessionStorage.js
  yarn.lock
Labels: :hammer: refactor

#145 [refactor] base 컴포넌트 style 코드 리팩터링 - 2
  src/components/base/Modal/index.jsx
  src/components/base/Modal/styles.js
  src/components/base/Pagination/index.jsx
  src/components/base/Pagination/styles.js
  src/components/base/Spinner/index.jsx
  src/components/base/Spinner/styles.js
  src/components/base/Tag/TagInput.jsx
  src/components/base/Tag/TagItem.jsx
  src/components/base/Tag/index.jsx
  src/components/base/Tag/styles.js
  src/components/base/Text/index.jsx
  src/components/base/Textarea/index.jsx
  src/components/base/Textarea/styles.js
  src/components/base/Toast/ToastItem.jsx
  src/components/base/Toast/index.jsx
  src/components/base/Toast/styles.js
Labels: :hammer: refactor

#148 [refactor] recoil을 활용한 유저 Token 관리부분 리팩터링
  package.json
  src/App.jsx
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/FloatingLikeButton/index.jsx
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/TemplateHeader/UserNav/Authorized.jsx
  src/components/domain/TemplateHeader/UserNav/index.jsx
  src/context/AuthProvider.jsx
  src/hooks/useAuth.js
  src/pages/JoinGroup.jsx
  src/pages/MyGroup.jsx
  src/pages/MyPage.jsx
  src/pages/SignIn.jsx
  src/pages/TIL.jsx
  src/stores/auth.js
  src/stores/user.js
  yarn.lock
Labels: :hammer: refactor

#150 [refactor] recoil, react query 도입
  package.json
  src/App.jsx
  src/api/notification.js
  src/api/post.js
  src/components/base/Tag/TagInput.jsx
  src/components/base/Toast/ToastItem.jsx
  src/components/base/Toast/index.jsx
  src/components/domain/AlarmModal/index.jsx
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CommentList/index.jsx
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupItem/index.jsx
  src/components/domain/ManageGroup/GroupDelete.jsx
  src/components/domain/ManageGroup/ManageMember.jsx
  src/components/domain/ManageGroup/UpdateGroupInfo.jsx
  src/components/domain/SettingModal/index.jsx
  src/components/domain/SettingModal/styles.js
  src/components/domain/TILList/index.jsx
  src/components/domain/TemplateHeader/SearchBar.jsx
  src/components/domain/TemplateHeader/UserNav/Authorized.jsx
  src/context/CommentProvider.jsx
  src/context/LikeProvider.jsx
  src/context/TILProvider.jsx
  src/context/ToastProvider.jsx
  src/context/UserProvider.jsx
  src/hooks/queries/comments.js
  src/hooks/queries/likes.js
  src/hooks/queries/notifications.js
  src/hooks/queries/tils.js
  src/hooks/useToasts.js
  src/pages/ManageGroup.jsx
  src/pages/MyPage.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/TIL.jsx
  src/pages/TILEditor.jsx
  src/stores/toasts.js
  src/stores/users.js
  yarn.lock
Labels: :hammer: refactor

#157 [feat] 검색 후 검색값을 input창에 남겨놓기
  src/components/domain/TemplateHeader/SearchBar.jsx
Labels: ✨ feat

#152 [refactor] 일부 base component 수정
  src/components/base/Avatar/index.jsx
  src/components/base/Button/index.jsx
  src/components/base/Input/index.jsx
  src/components/base/Tag/TagInput.jsx
  src/components/base/Tag/TagItem.jsx
  src/components/base/Tag/styles.js
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupItem/styles.js
Labels: 🐛 fix, :hammer: refactor

#158 [feat] 헤더 반응형 추가
  src/components/domain/AlarmModal/styles.js
  src/components/domain/HamburgerModal/index.jsx
  src/components/domain/HamburgerModal/styles.js
  src/components/domain/TemplateHeader/Logo.jsx
  src/components/domain/TemplateHeader/UserNav/Authorized.jsx
  src/components/domain/TemplateHeader/styles.js
  src/components/template/index.jsx
  src/components/template/styles.js
  src/stores/searchBar.js
  src/styles/keyframes.js
Labels: ✨ feat

#161 [fix] TIL카드에 마크다운 표시되던 문제 수정
  src/components/domain/TILItem/index.jsx
  src/components/domain/TILItem/styles.js
  src/utils/cleanMarkdown.js
Labels: ✨ feat, 🐛 fix

#167 [feat] 검색 결과 페이지 반응형
  src/components/domain/SearchResult/SearchResultContainer.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/SearchResult/styles.js
  src/pages/SearchResult.jsx
Labels: ✨ feat, 🎨 design

#163 [feat] 내 정보 페이지 반응형
  src/components/template/styles.js
  src/pages/MyPage.jsx
Labels: ✨ feat
