Repository prgrms-fe-devcourse/FEDC3_SWithMe_Gidong, pull requests merged in 2023-01, with the labels that each got.

#5 [design] 내 그룹 페이지 스타일링
  .eslintrc.json
  index.html
  src/Router.jsx
  src/assets/icons/index.jsx
  src/assets/images/img_puzzle.png
  src/assets/images/index.js
  src/assets/images/index.jsx
  src/components/.gitkeep
  src/components/base/.gitkeep
  src/components/base/Header/index.jsx
  src/components/base/Image/index.jsx
  src/components/base/Text/index.jsx
  src/pages/MyGroup.jsx
  src/stories/components/.gitkeep
  src/stories/components/base/.gitkeep
  src/stories/components/base/Header.stories.jsx
  src/stories/components/base/Image.stories.jsx
  src/stories/components/base/Text.stories.jsx
  src/styles/color.js
Labels: 🎨 design

#9 [feat] 채널 정보 불러오는 API 연결
  src/api/channel.js
  src/api/core/index.js
  src/utils/storage.js
Labels: 📡 API

#17 [feat] 그룹 내 TIL 목록 보여주기
  src/api/post.js
  src/assets/images/img_TIL.png
  src/assets/images/index.jsx
  src/components/base/Empty/index.jsx
  src/components/base/Spinner/index.jsx
  src/components/base/index.js
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/TILItem/index.jsx
  src/components/domain/TILList/index.jsx
  src/context/GroupProvider.jsx
  src/context/TILProvider.jsx
  src/pages/MyGroup.jsx
  src/styles/color.js
  src/utils/api.js
Labels: ✨ feat, 🎨 design, 📡 API

#18 [design] 그룹 정보 모달 레이아웃
  src/components/base/Avatar/index.jsx
  src/components/base/Icon/index.jsx
  src/components/base/Image/index.jsx
  src/components/base/Input/index.jsx
  src/components/base/Modal/index.jsx
  src/components/base/SearchBar/index.jsx
  src/components/base/Tag/TagItem.jsx
  src/components/base/Tag/TagList.jsx
  src/components/base/Tag/index.jsx
  src/components/base/Text/index.css
  src/components/base/Text/index.jsx
  src/components/base/Textarea/index.jsx
  src/components/base/index.js
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/groupInfo/Introduction.jsx
  src/components/domain/groupInfo/Member.jsx
  src/components/domain/groupInfo/MemberList.jsx
  src/components/domain/groupInfo/index.jsx
  src/stories/components/base/Avatar.stories.jsx
  src/stories/components/domain/.gitkeep
  src/stories/components/domain/GroupInfoModal.stories.jsx
  src/styles/color.js
Labels: ✨ feat, 🎨 design, :hammer: refactor

#20 [feat] 회원가입 기능 구현
  src/api/signup.js
  src/pages/SignUp.jsx
  src/styles/color.js
Labels: ✨ feat, 📡 API

#28 [feat] 기본 라우터 설정
  src/App.jsx
  src/Router.jsx
  src/assets/icons/ic_search_submit.svg
  src/components/base/Divider/index.jsx
  src/components/domain/Header/HeaderLogo.jsx
  src/components/domain/Header/HeaderSearchBar.jsx
  src/components/domain/Header/HeaderUserNav.jsx
  src/components/domain/Header/UserNavButton.jsx
  src/components/domain/Header/UserSignInButton.jsx
  src/components/domain/Header/index.jsx
  src/pages/MyGroup.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/styles/color.js
Labels: ✨ feat, 🎨 design

#25 [design] TIL 작성 페이지 레이아웃
  package.json
  src/Router.jsx
  src/components/base/Button/index.jsx
  src/components/base/SearchBar/index.jsx
  src/components/base/Tag/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/TILList/index.jsx
  src/pages/WriteTIL.jsx
  yarn.lock
Labels: ✨ feat, 🎨 design

#29 [feat] 그룹 오픈시 디테일 구현
  package.json
  src/App.jsx
  src/components/base/Calendar/index.jsx
  src/components/base/Pagination/index.jsx
  src/components/base/index.js
  src/components/domain/GroupItem/index.jsx
  src/components/domain/TILItem/index.jsx
  src/components/domain/TILList/index.jsx
  src/pages/MyGroup.jsx
  src/styles/datepicker_custom.css
  yarn.lock
Labels: ✨ feat, 🎨 design

#31 [design] TIL 보기 페이지 레이아웃
  src/Router.jsx
  src/assets/images/img_default_avatar.png
  src/assets/images/index.jsx
  src/components/base/Icon/index.jsx
  src/components/base/Icon/index.scss
  src/components/base/Textarea/index.jsx
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CommentList/index.jsx
  src/components/domain/TILItem/index.jsx
  src/pages/TIL.jsx
  src/utils/date.js
Labels: ✨ feat, 🎨 design

#33 [feat] 마이 페이지 작성 및 로그인 상태 관리
  src/Router.jsx
  src/api/userSign.js
  src/assets/images/img_mypage.png
  src/assets/images/img_user_avatar.png
  src/assets/images/index.jsx
  src/components/domain/Header/HeaderUserNav.jsx
  src/components/domain/Header/index.jsx
  src/pages/MyPage.jsx
  src/styles/color.js
  src/utils/storage.js
Labels: ✨ feat, 🎨 design, 📡 API

#35 [feat] 그룹 가입 신청 페이지 구현
  package.json
  src/Router.jsx
  src/assets/icons/ic_crown.svg
  src/assets/icons/ic_logo.svg
  src/assets/icons/index.jsx
  src/assets/images/img_logo.png
  src/assets/images/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/Header/HeaderLogo.jsx
  src/components/domain/Header/HeaderSearchBar.jsx
  src/components/domain/Header/HeaderUserNav.jsx
  src/components/domain/Header/index.jsx
  src/pages/JoinGroup.jsx
  src/pages/MyGroup.jsx
  src/styles/color.js
  yarn.lock
Labels: ✨ feat, 🎨 design

#34 [feat] TIL 수정 페이지 레이아웃
  src/Router.jsx
  src/components/base/Tag/index.jsx
  src/pages/TIL.jsx
  src/pages/TILEditor.jsx
  src/utils/validation.js
Labels: ✨ feat, 🎨 design

#40 [hotfix] conflict 해결할 때 사라진 라인 복구
  src/Router.jsx
Labels: 🐛 fix

#41 [feat] 로그인한 유저 정보 전역으로 관리
  src/App.jsx
  src/api/userSign.js
  src/components/domain/Header/HeaderUserNav.jsx
  src/context/AuthProvider.jsx
  src/pages/SignIn.jsx
Labels: ✨ feat

#47 feat: 그룹 정보 모달 연결 및 그룹 삭제 api 연동
  src/App.jsx
  src/api/channel.js
  src/api/post.js
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupItem/index.jsx
  src/components/domain/groupInfo/Member.jsx
  src/context/GroupProvider.jsx
  src/pages/MyGroup.jsx
Labels: ✨ feat, 📡 API

#45 [feat] 그룹 가입 신청 api 연결
  src/api/channel.js
  src/api/post.js
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupList/index.jsx
  src/pages/JoinGroup.jsx
Labels: ✨ feat, 📡 API

#49 [feat] TIL 작성 페이지 API 연동
  src/api/post.js
  src/components/base/Modal/index.jsx
  src/context/TILProvider.jsx
  src/pages/TILEditor.jsx
Labels: ✨ feat, 📡 API

#52 [feat] TIL 삭제 API 연동
  src/api/post.js
  src/context/TILProvider.jsx
  src/pages/TIL.jsx
Labels: ✨ feat, 📡 API

#57 [feat] 그룹 관리 페이지 구현
  src/App.jsx
  src/Router.jsx
  src/api/channel.js
  src/components/domain/GroupItem/index.jsx
  src/context/GroupProvider.jsx
  src/pages/JoinGroup.jsx
  src/pages/ManageGroup.jsx
  src/styles/color.js
Labels: ✨ feat, 🎨 design, 📡 API

#60 [feat] TIL 보기 페이지 api 연동
  src/App.jsx
  src/api/comment.js
  src/api/like.js
  src/api/post.js
  src/components/domain/CommentItem/index.jsx
  src/components/domain/TILItem/index.jsx
  src/context/CommentProvider.jsx
  src/context/LikeProvider.jsx
  src/context/TILProvider.jsx
  src/pages/TIL.jsx
Labels: ✨ feat, 📡 API

#62 [feat] 헤더 추가 스타일링
  src/assets/icons/ic_alert_off.svg
  src/assets/icons/ic_alert_on.svg
  src/assets/icons/ic_my_group.svg
  src/assets/icons/ic_my_info.svg
  src/assets/icons/index.jsx
  src/components/domain/Header/HeaderDropdownItem.jsx
  src/components/domain/Header/HeaderIcon.jsx
  src/components/domain/Header/HeaderSearchBar.jsx
  src/components/domain/Header/HeaderUserNav.jsx
  src/components/domain/Header/index.jsx
  src/components/domain/MyPage/MyPageButton.jsx
  src/components/domain/MyPage/index.jsx
  src/pages/MyPage.jsx
  src/styles/color.js
Labels: 🎨 design, 🍭 chore

#64 [design] 그룹 검색 페이지 스타일링
  src/components/domain/SearchResult/SearchResultContainer.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/SearchResult/index.jsx
  src/pages/SearchResult.jsx
Labels: ✨ feat, 🎨 design

#68 fix: 그룹 정보 모달에서 탈퇴하기로 변경, 그룹 description 수정
  src/App.jsx
  src/api/user.js
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupList/index.jsx
  src/context/GroupProvider.jsx
  src/context/UserProvider.jsx
  src/pages/ManageGroup.jsx
  src/pages/SignUp.jsx
Labels: ✨ feat, 🐛 fix

#69 [feat] 알림 모달 레이아웃
  src/components/domain/AlarmModal/index.jsx
  src/components/domain/Header/HeaderUserNav.jsx
Labels: ✨ feat, 🎨 design

#71 [feat] 알림 모달 api 연동
  .eslintrc.json
  src/App.jsx
  src/api/alarm.js
  src/components/domain/AlarmModal/index.jsx
  src/components/domain/CommentItem/index.jsx
  src/context/CommentProvider.jsx
  src/context/LikeProvider.jsx
  src/pages/TIL.jsx
Labels: ✨ feat, 📡 API

#72 [feat] 홈 페이지 구현
  src/Router.jsx
  src/assets/images/img_home_illust.png
  src/assets/images/index.jsx
  src/components/domain/Header/index.jsx
  src/components/domain/TILList/index.jsx
  src/pages/Home.jsx
Labels: ✨ feat, 🎨 design

#74 [feat] 검색 기능 추가 및 템플릿 컴포넌트 작성
  src/Router.jsx
  src/components/domain/Header/HeaderDropdownItem.jsx
  src/components/domain/Header/HeaderSearchBar.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/TemplateHeader/Logo.jsx
  src/components/domain/TemplateHeader/NavIcon.jsx
  src/components/domain/TemplateHeader/SearchBar.jsx
  src/components/domain/TemplateHeader/UserNav.jsx
  src/components/domain/TemplateHeader/index.jsx
  src/components/template/.gitkeep
  src/components/template/index.jsx
  src/pages/SearchResult.jsx
  src/styles/color.js
Labels: ✨ feat, 🎨 design

#77 [feat] 검색 결과 페이지
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/TemplateHeader/SearchBar.jsx
  src/pages/SearchResult.jsx
Labels: ✨ feat, 📡 API

#78 [design] 로그인 / 회원가입 페이지 스타일링 수정
  src/assets/images/img_login.png
  src/assets/images/index.jsx
  src/components/domain/SignInput/index.jsx
  src/components/template/index.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/styles/globalStyle.jsx
Labels: 🎨 design

#82 [design] 홈, 내 그룹 페이지, TIL, 모달 디자인 수정
  src/components/base/Modal/index.jsx
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/GroupInfoModal/index.jsx
  src/pages/Home.jsx
  src/pages/MyGroup.jsx
  src/pages/TIL.jsx
  src/pages/TILEditor.jsx
Labels: 🎨 design

#81 [design] 마이페이지, 그룹 가입 페이지 디자인 수정
  .github/workflows/production.yaml
  src/assets/images/img_join.png
  src/assets/images/img_mypage.png
  src/assets/images/img_user_avatar.png
  src/assets/images/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/MyPage/MyPageButton.jsx
  src/pages/JoinGroup.jsx
  src/pages/MyPage.jsx
Labels: 🎨 design

#83 [design] 헤더, 검색결과 페이지 디자인 수정
  src/components/domain/SearchResult/SearchResultContainer.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/TemplateHeader/SearchBar.jsx
  src/pages/SearchResult.jsx
  src/styles/color.js
Labels: ✨ feat, 🎨 design
