Repository prgrms-fe-devcourse/FEDC3_SWithMe_Gidong, pull requests merged in 2023-03, with the labels that each got.

#120 [refactor] style 코드 분리 작업 (Base, A-I)
  src/components/base/Avatar/index.jsx
  src/components/base/Avatar/styles.js
  src/components/base/Badge/index.jsx
  src/components/base/Badge/styles.js
  src/components/base/Button/index.jsx
  src/components/base/Button/styles.js
  src/components/base/Button/view.jsx
  src/components/base/Calendar/index.jsx
  src/components/base/Calendar/styles.js
  src/components/base/Divider/index.jsx
  src/components/base/Divider/styles.js
  src/components/base/Empty/index.jsx
  src/components/base/Empty/styles.js
  src/components/base/Input/index.jsx
  src/components/base/Input/styles.js
  src/styles/color.js
Labels: 🍭 chore, :hammer: refactor

#121 [refactor] style 코드 분리 작업 (Base, J-Z)
  src/components/base/Modal/index.jsx
  src/components/base/Modal/styles.js
  src/components/base/Pagination/index.jsx
  src/components/base/Pagination/styles.js
  src/components/base/SearchBar/index.jsx
  src/components/base/SearchBar/styles.js
  src/components/base/Spinner/index.jsx
  src/components/base/Spinner/styles.js
  src/components/base/Tag/TagInput.jsx
  src/components/base/Tag/TagItem.jsx
  src/components/base/Tag/index.jsx
  src/components/base/Tag/styles.js
  src/components/base/Textarea/index.jsx
  src/components/base/Textarea/styles.js
  src/components/base/Toast/ToastItem.jsx
  src/components/base/Toast/index.jsx
  src/components/base/Toast/styles.js
  src/components/base/index.js
  src/styles/color.js
Labels: 🍭 chore, :hammer: refactor

#124 [refactor] domain 컴포넌트 스타일 코드 분리
  src/components/base/Button/View.jsx
  src/components/base/Button/styles.js
  src/components/domain/AlarmModal/index.jsx
  src/components/domain/AlarmModal/styles.js
  src/components/domain/AuthorNav/index.jsx
  src/components/domain/AuthorNav/styles.js
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CommentItem/styles.js
  src/components/domain/CommentList/index.jsx
  src/components/domain/CommentList/styles.js
  src/components/domain/CreateComment/index.jsx
  src/components/domain/CreateComment/styles.js
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/CreateGroupModal/styles.js
  src/components/domain/FloatingLikeButton/index.jsx
  src/components/domain/FloatingLikeButton/styles.js
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupInfoModal/styles.js
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupItem/styles.js
  src/components/domain/GroupList/index.jsx
  src/components/domain/GroupList/styles.js
  src/components/domain/ManageGroup/GroupDelete.jsx
  src/components/domain/ManageGroup/ManageMember.jsx
  src/components/domain/ManageGroup/UpdateGroupInfo.jsx
  src/components/domain/ManageGroup/styles.js
  src/components/domain/ManageGroup/styles.jsx
  src/components/domain/SearchResult/SearchResultContainer.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/SearchResult/styles.js
  src/components/domain/SettingModal/index.jsx
  src/components/domain/SettingModal/styles.js
  src/components/domain/SignInput/index.jsx
  src/components/domain/SignInput/styles.js
  src/components/domain/TILItem/index.jsx
  src/components/domain/TILItem/styles.js
  src/components/domain/TILList/index.jsx
  src/components/domain/TILList/styles.js
  src/components/domain/TemplateHeader/Logo.jsx
  src/components/domain/TemplateHeader/SearchBar.jsx
  src/components/domain/TemplateHeader/UserNav/index.jsx
  src/components/domain/TemplateHeader/styles.js
  src/components/domain/groupInfo/Introduction.jsx
  src/components/domain/groupInfo/Member.jsx
  src/components/domain/groupInfo/MemberList.jsx
  src/components/domain/groupInfo/styles.js
Labels: :hammer: refactor

#125 [refactor] base 컴포넌트 props 값 사전 정의 - 1
  src/assets/images/img_user_avatar.png
  src/assets/images/index.jsx
  src/components/base/Avatar/index.jsx
  src/components/base/Avatar/styles.js
  src/components/base/Badge/index.jsx
  src/components/base/Divider/index.jsx
  src/components/base/Divider/styles.js
  src/components/base/Image/index.jsx
  src/components/domain/AlarmModal/index.jsx
  src/components/domain/CommentItem/index.jsx
  src/components/domain/CommentList/index.jsx
  src/components/domain/GroupItem/index.jsx
  src/components/domain/SettingModal/index.jsx
  src/components/domain/TILList/index.jsx
  src/components/domain/TemplateHeader/UserNav/Authorized.jsx
  src/components/domain/groupInfo/Member.jsx
  src/pages/Home.jsx
  src/pages/JoinGroup.jsx
  src/pages/MyGroup.jsx
  src/pages/MyPage.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/TIL.jsx
Labels: :hammer: refactor

#127 [refactor] base 컴포넌트 props 값 사전 정의 - 2
  package.json
  src/components/base/Empty/index.jsx
  src/components/base/Header/index.jsx
  src/components/base/Heading/index.jsx
  src/components/base/Icon/index.jsx
  src/components/base/Icon/index.scss
  src/components/base/Icon/styles.js
  src/components/base/index.js
  src/components/domain/AlarmModal/index.jsx
  src/components/domain/CreateGroupModal/index.jsx
  src/components/domain/FloatingLikeButton/index.jsx
  src/components/domain/GroupInfoModal/index.jsx
  src/components/domain/GroupItem/index.jsx
  src/components/domain/GroupList/index.jsx
  src/components/domain/ManageGroup/GroupDelete.jsx
  src/components/domain/ManageGroup/ManageMember.jsx
  src/components/domain/ManageGroup/UpdateGroupInfo.jsx
  src/components/domain/ManageGroup/styles.js
  src/components/domain/SearchResult/SearchResultContainer.jsx
  src/components/domain/SearchResult/SearchResultGroup.jsx
  src/components/domain/TILList/index.jsx
  src/components/domain/TemplateHeader/Logo.jsx
  src/components/domain/TemplateHeader/SearchBar.jsx
  src/components/domain/TemplateHeader/UserNav/Authorized.jsx
  src/components/domain/groupInfo/Member.jsx
  src/components/template/index.jsx
  src/pages/JoinGroup.jsx
  src/pages/MyGroup.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/TIL.jsx
  src/pages/TILEditor.jsx
  src/stories/components/base/Header.stories.jsx
  yarn.lock
Labels: :hammer: refactor

#130 [refactor] Template 컴포넌트 스타일 코드 분리
  src/components/template/index.jsx
  src/components/template/styles.js
Labels: :hammer: refactor

#132 [refactor] axios 인스턴스 코드 리팩토링
  .eslintrc.json
  src/api/core/index.js
Labels: :hammer: refactor, 📡 API

#136 [feat] custom theme 코드 작성
  src/styles/theme.js
Labels: ✨ feat, 🎨 design

#138 [refactor] base 컴포넌트 style 코드 리팩터링 - 1
  src/App.jsx
  src/components/base/Avatar/index.jsx
  src/components/base/Avatar/styles.js
  src/components/base/Badge/index.jsx
  src/components/base/Badge/styles.js
  src/components/base/Button/index.jsx
  src/components/base/Button/styles.js
  src/components/base/Calendar/index.jsx
  src/components/base/Calendar/styles.js
  src/components/base/Divider/index.jsx
  src/components/base/Divider/styles.js
  src/components/base/Empty/index.jsx
  src/components/base/Empty/styles.js
  src/components/base/Heading/index.jsx
  src/components/base/Icon/index.jsx
  src/components/base/Icon/styles.js
  src/styles/theme.js
Labels: :hammer: refactor
